package com.bis.ca2is4448.Model;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

//Generated by https://www.jsonschema2pojo.org/
public class Hero {

    @SerializedName("id")
    @Expose
    private Integer id;
    @SerializedName("name")
    @Expose
    private String name;
    @SerializedName("realname")
    @Expose
    private String realname;
    @SerializedName("rating")
    @Expose
    private int rating;
    @SerializedName("teamaffiliation")
    @Expose
    private String teamaffiliation;

    /**
     * No args constructor for use in serialization
     *
     */
    public Hero() {
    }

    /**
     *
     * @param name
     * @param rating
     * @param teamaffiliation
     * @param id
     * @param realname
     */
    public Hero(int id, String name, String realname, int rating, String teamaffiliation) {
        super();
        this.id = id;
        this.name = name;
        this.realname = realname;
        this.rating = rating;
        this.teamaffiliation = teamaffiliation;
    }

    public Hero(String name, String realname, int rating, String teamaffiliation) {
        this.name = name;
        this.realname = realname;
        this.rating = rating;
        this.teamaffiliation = teamaffiliation;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getRealname() {
        return realname;
    }

    public void setRealname(String realname) {
        this.realname = realname;
    }

    public int getRating() {
        return rating;
    }

    public void setRating(int rating) {
        this.rating = rating;
    }

    public String getTeamaffiliation() {
        return teamaffiliation;
    }

    public void setTeamaffiliation(String teamaffiliation) {
        this.teamaffiliation = teamaffiliation;
    }

}
