package com.bis.ca2is4448.Model;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.util.List;

//Generated by https://www.jsonschema2pojo.org/
public class JSONResponseModel {

    @SerializedName("error")
    @Expose
    private boolean error;
    @SerializedName("message")
    @Expose
    private String message;
    @SerializedName("heroes")
    @Expose
    private List<Hero> heroes = null;

    /**
     * No args constructor for use in serialization
     *
     */
    public JSONResponseModel() {
    }

    /**
     *
     * @param heroes
     * @param error
     * @param message
     */
    public JSONResponseModel(boolean error, String message, List<Hero> heroes) {
        super();
        this.error = error;
        this.message = message;
        this.heroes = heroes;
    }

    public boolean isError() {
        return error;
    }

    public void setError(boolean error) {
        this.error = error;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public List<Hero> getHeroes() {
        return heroes;
    }

    public void setHeroes(List<Hero> heroes) {
        this.heroes = heroes;
    }


}
